(function(l){var h=window.AmazonUIPageJS||window.P,k=h._namespace||h.attributeErrors,d=k?k("AmazonLiveReactAssetsBuild@poller","AmazonLiveReact"):h;d.guardFatal?d.guardFatal(l)(d,window):d.execute(function(){l(d,window)})})(function(l,h,k){!function(d){function a(c){if(e[c])return e[c].exports;var b=e[c]={i:c,l:!1,exports:{}};return d[c].call(b.exports,b,b.exports,a),b.l=!0,b.exports}var e={};a.m=d;a.c=e;a.d=function(c,b,f){a.o(c,b)||Object.defineProperty(c,b,{configurable:!1,enumerable:!0,get:f})};
a.r=function(c){Object.defineProperty(c,"__esModule",{value:!0})};a.n=function(c){var b=c&&c.__esModule?function(){return c.default}:function(){return c};return a.d(b,"a",b),b};a.o=function(c,b){return Object.prototype.hasOwnProperty.call(c,b)};a.p="";a(a.s=6)}([function(d,a){d.exports=Globals},,function(d,a,e){Object.defineProperty(a,"__esModule",{value:!0});a.triggerEvents=void 0;var c=function(b){return b&&b.__esModule?b:{default:b}}(e(0));a.triggerEvents=function(b){null!=b&&(Object.keys(b).forEach(function(a){var m=
b[a];Object.keys(m).forEach(function(b){c.default.A.trigger("amazonLiveEvent:"+a+":"+b,m[b])})}),c.default.A.$.isEmptyObject(b)||c.default.A.state("amazonLiveState",b))}},function(d,a,e){Object.defineProperty(a,"__esModule",{value:!0});var c=function(){function b(m,r){for(var c=0;c<r.length;c++){var a=r[c];a.enumerable=a.enumerable||!1;a.configurable=!0;"value"in a&&(a.writable=!0);Object.defineProperty(m,a.key,a)}}return function(a,c,g){return c&&b(a.prototype,c),g&&b(a,g),a}}(),b=function(b){return b&&
b.__esModule?b:{default:b}}(e(0));d=function(){function a(){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");!0;this.currentState=null}return c(a,[{key:"computeEventsByDifference",value:function(a){var c=this;if(null==a)return{};if(null==this.currentState)return this.currentState=a,a;var g={};return Object.keys(a).forEach(function(d){var e={},f=a[d],h=c.currentState[d];Object.keys(f).forEach(function(a){var c=f[a];b.default.A.equals(c,h[a])||(e[a]=c)});b.default.A.$.isEmptyObject(e)||
(g[d]=e)}),this.currentState=a,g}},{key:"getBroadcastEvents",value:function(a){var b=a.broadcastEventsData;return null==b?(console.warn("Couldn't parse event service response. Received state: "),console.warn(a),null):this.computeEventsByDifference(b)}}]),a}();a.default=d},function(d,a,e){Object.defineProperty(a,"__esModule",{value:!0});var c=function(){function a(b,c){for(var d=0;d<c.length;d++){var e=c[d];e.enumerable=e.enumerable||!1;e.configurable=!0;"value"in e&&(e.writable=!0);Object.defineProperty(b,
e.key,e)}}return function(b,c,d){return c&&a(b.prototype,c),d&&a(b,d),b}}(),b=function(a){return a&&a.__esModule?a:{default:a}}(e(0)),f=void 0;b.default.A.on("amazonLiveEvent:pageController:poller:urlOverride",function(a){a!==f&&(f=a)});b.default.A.on("amazonLiveEvent:pageController:poller:clearUrlOverride",function(){f&&(f=void 0)});d=function(){function a(b){var c=b.host;b=b.asinList;if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");!0;this.baseUrl=c;this.asinList=
b}return c(a,[{key:"constructUrl",value:function(){var a=this.baseUrl;return this.asinList.forEach(function(b){a=a+(-1<a.indexOf("?")?"\x26":"?")+"asin\x3d"+b}),a}},{key:"pollBroadcastState",value:function(a,c){var d=f||this.constructUrl();a={success:a,error:c,withCredentials:!0};this.ajaxHandler&&this.ajaxHandler.abort();c=new Date;c.setMilliseconds(0);b.default.A.trigger("amazonlive:poller:requestTime",c);this.ajaxHandle=b.default.A.get(d,a)}}]),a}();a.default=d},function(d,a,e){function c(a){return a&&
a.__esModule?a:{default:a}}var b=c(e(0)),f=c(e(4)),m=c(e(3)),l=e(2),g=1.5,n=3E3,p=n,k=6E4,t=void 0,q=!0,u=void 0,v=void 0,w=function(a){a=v.getBroadcastEvents(a);(0,l.triggerEvents)(a);p=n},x=function(a,b,c){console.warn("[POLLER] AmazonLivePageController Error in Polling the endpoint for BroadcastStateService. Received error: "+c);clearTimeout(t);q=!1;p=Math.min(p*g,k);console.warn("Waiting at least "+p+" ms and try again.");t=setTimeout(function(){q=!0},p)};d=function(){v=new m.default;(function(){var a=
function(){var a=b.default.A.state("amazonlive-react-poller-data");if(null==a)return console.warn("Missing Config in aui state"),null;var c=a.pollAsinList;if(null==c||0===c.length)return console.warn("Missing pollAsinList in Poller Config"),null;var d=a.pollerConfig;if(null==d)return console.warn("Missing pollerConfig in Poller Config"),null;Object.assign(d,function(a){return h.reduxStore?"T1"!==reduxStore.getState().weblab.pollerConfigCarouselHighlightLatencyOverride?{}:a.pollerConfigCarouselHighlightLatencyOverride||
(console.warn("Missing pollerConfigCarouselHighlightLatencyOverride in Poller Config"),{}):(console.warn("Missing reduxStore"),{})}(a));a=d.broadcastStateUrl;if(null==a)return console.warn("Missing broadcastStateUrl in Poller Config"),null;g=d.backOffFactor||g;n=d.defaultWaitTimeMillis||n;k=d.maxWaitTimeMillis||k;return new f.default({asinList:c,host:a})}();null!=a?u=setInterval(function(){q&&a.pollBroadcastState(w,x)},n):console.warn("Failed to initialize Poller")})()};b.default.A.on("amazonLiveEvent:pageController:poller:isEnabled",
function(a){q=a});b.default.A.on("amazonlive-poller-enabled",d);b.default.A.on("amazonlive-poller-disabled",function(){clearInterval(u)});d()},function(d,a,e){l.when("A","amazonlive-react-rendered","amazonlive-poller-enabled","ready").register("amazon-live-page-controller",function(){e(5)})}])});